---
flighdeck_motd_name: Solr 6.6

flightdeck_groups:
  - name: "solr"

flightdeck_users:
  - name: "solr"
    group: "solr"
    home: "/home/solr"

flightdeck_root_prompt: '\u@flight-deck-solr:\w# '
flightdeck_user_prompt: '\u@flight-deck-solr:\w$ '

flightdeck_run_commands: |
  if [ -f "/config/flight-deck-solr.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/flight-deck-solr.yml" /ansible/run.yml {{ flightdeck_debug | ternary('-vvvv', '') }}
  else
    ansible-playbook -i /ansible/inventories/all.ini /ansible/run.yml {{ flightdeck_debug | ternary('-vvvv', '') }}
  fi

flightdeck_path:
  - '/opt/solr/bin'

flightdeck_solr:
  port: "8983"
  cores: []
    # - name: "mysite_live"
    #   type: "search_api_solr"
    # - name: "othersite_live"
    #   type: "apachesolr"
    # - name: "blah"
    #   type: "custom"
    #   confDir: "/config/blah"
    #   dataDir: "/data/blah"
